### ISSUE TITLE
Weird Corrupted Symbols In Follower Notifications

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#1]
Original report by @TheRealDannyyy: https://github.com/Scirra/Construct-3-bugs/issues/1302

## Problem description

The follower notifications have a weird symbol that's probably not supposed to be there.

## Example Image

![notificationbug](https://user-images.githubusercontent.com/15656049/36430681-1a9bbc78-1656-11e8-8dfd-b3cfbc6db62e.PNG)

## Steps to reproduce

1. Open C3 notifications
2. Let someone follow you
3. Notice weird symbol

## Observed result

Just a weird symbol, everything else works fine.

## Expected result

No weird symbol.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: -
* Safari: -

**Comment by phillscirra** [comment]
Yeah, I think this one is fixed, but there are a few other types of symbol difficult to weed out whilst searching in the code base.

**Comment by TheRealDannyyy** [comment]
I will always report back when I find some more of these.
