### ISSUE TITLE
Any page on scirra.com returns Error 522 Connection timed out

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#101]
## Problem description

Any page on scirra.com returns Error 522 Connection timed out, can't download new version of C2.
Tried from VPN with German IP - same result.

## Steps to reproduce

Open scirra.com

## Observed result

Error 522 Connection timed out error.

## Expected result

Not that.

**Comment by AshleyScirra** [comment]
Seems to be working again so I think this is referring to [this resolved outage](https://twitter.com/ConstructTeam/status/1132398769432088576) so closing.
