### ISSUE TITLE
[NW.JS export]Unable to load NW.js versions

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#102]
## Problem description

When trying to export using NW.JS, the NW.JS options dialog does not allow to download/access NW.JS.

## Attach a .c3p

Open a new project

## Steps to reproduce

1. Export using Desktop (NW.js) option
2. Click next in the Export options dialog

## Observed result

An error message appears :
Unable to load NW.js versions. Check your Internet connection is working. (spoiler: my connexion is working)

Clicking the OK button closes the dialog, without any possibility to download NW.js and export using it.

## Expected result

To be able to manage and download the NW.js version as it was possible in the past.

## More details

**Affected browsers/platforms:** 

**First affected release:**
Seen in r150 beta
Happens as well in Stable R136

My gut feeling is this is a server issue and nothing to do with the release or client's computer the editor is executed on.

**Comment by AshleyScirra** [comment]
The NW.js files are served by the website so moved to website issues.

For some reason I can export from C3 in the office (I guess it's cached locally), but I'm getting a 525 error on downloads.scirra.com, e.g.: https://downloads.scirra.com/c3-nwjs/versions.json

**Comment by TomGullen** [comment]
Should be fixed now.
