### ISSUE TITLE
Affiliate tag getting cropped

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct.net-website-bugs#107]
## Problem description

![image](https://user-images.githubusercontent.com/11213825/60767109-fbc31600-a0b2-11e9-99cc-6cb687d0cf56.png)

The affiliate text is cropped

## Steps to reproduce

1. Open that link: https://www.construct.net/fr/blogs/skymen-13

## Observed result

The affiliate text is cropped

## Expected result

The affiliate text should not be cropped

**Comment by TomGullen** [comment]
Fixed in next upload
