### ISSUE TITLE
Uploading image to add to a post in the forums does not work.

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#111]
## Problem description

Uploading image to add to a post in the forums does not work.

## Steps to reproduce

1. Create a new post
2. Click the "Add image" button
3. Select an image to upload, click the "Upload image button

## Observed result

A bar "Upload" quickly displays, goes full, and disappears, leaving the "Upload dialog" up, and not providing the ID for the uploaded file in the appropriate bbcode tag.

## Expected result

The dialog to disappear, the tag to appear, the image to be added.

**Comment by TomGullen** [comment]
Fixed next upload
