### ISSUE TITLE
Minor issue with post bottom-margins

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#112]
## Problem description
Lists at the end of a post seem to break the bottom-margins.
(Not sure if it also applies to other types of lists.)

## Observed result
![image](https://user-images.githubusercontent.com/15656049/62139725-1f603180-b2ea-11e9-8bfb-60b6615885b1.png)

## Expected result
Few pixels of bottom-margin like in [the post above](https://www.construct.net/en/forum/construct-2/general-discussion-17/cant-update-steam-to-version-145695).

**Comment by TomGullen** [comment]
Improved in next upload
