### ISSUE TITLE
Critical Error and Error 500 on the forum

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#115]
## Problem description

Since yesterday when browsing the forum very often one of the following two errors is displayed:

<details><summary>Critical Error</summary>

Critical error

This should not of happened. Please contact support.
System.IndexOutOfRangeException: Index was outside the bounds of the array. at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.OnSubscribed(RedisChannel channelName) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Redis\PubSub\PubSubController.cs:line 58 at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.SubscribeToCacheKey(RedisChannel cacheKey, Action`2 onMessageReceived) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Redis\PubSub\PubSubController.cs:line 46 at C3.Code.Controls.Application.Caching.Manager.Manager.Callbacks.OnGotten[T](String cacheKey, CacheType fromType, T objectGot) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Callbacks.cs:line 99 at C3.Code.Controls.Application.Caching.Manager.Manager.Get[T](String key, Func`1 getFromExternFunction, Boolean skipLocalCaches) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Manager.cs:line 125 at C3.Code.CachingNew.Get.ByID[T](Object objectID) in C:\Construct.net\Source\C3Alpha2\Code\CachingNew\Get.cs:line 118 at C3.Code.Helpers.SystemMessages.Reports.CreateSystemMessage(String title, String reportData, MessageType messageType, String ipAddress, Int32 cap) in C:\Construct.net\Source\C3Alpha2\Code\Helpers\SystemMessages\CreateReport.cs:line 41 at C3.Code.Helpers.Error.Functions.RecordError(Exception exception) in C:\Construct.net\Source\C3Alpha2\Code\Helpers\Error\Functions.cs:line 75 at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
</details>

<details><summary>Error 500</summary>

WHOOPS!
The server returned a 500 exception. This has been recorded and will be looked at by an engineer shortly. Sorry!
</details>

## Steps to reproduce

Browse the forum

## Observed result

Errors on most pages. Have to reload every page multiple times before it displays normally.

## Expected result

No errors.

**Comment by AshleyScirra** [comment]
Both web servers were rebooted and this seems to have cleared this up. Is it fixed on your end too?

**Comment by dop2000** [comment]
It was working fine for some time, but now it's happening again...

**Comment by RichardAstrom** [comment]
I'm getting this constantly as well.

**Comment by AshleyScirra** [comment]
We've implemented a fix for this, is it working better now?

**Comment by RichardAstrom** [comment]
Yes, it seems to be working fine now!
