### ISSUE TITLE
Request to add a 'Lock' feature for topics, for example depreciated ones.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct.net-website-bugs#116]
## Information

Request to add a **Lock** feature for topic owners, for specific scenarios like:
- depreciated topics
- migrated topics
- out-of-date, etc.

**Thanks.**

**Comment by AshleyScirra** [comment]
Please post website feature requests to the feature suggestion platform in the 'website' category.

**Comment by Chadori** [comment]
Alright.

**Comment by Chadori** [comment]
https://construct3.ideas.aha.io/ideas/C3-I-1069

**Thanks.**
