### ISSUE TITLE
Can't embed video hosted by 3rd party service

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#118]
## Problem description

The forum allows embedding of images by 3rd party hosters. Would be nice if there was a way to embed videos from 3rd party hosters as well.

## Observed result

Currently the only way to share videos is by creating a link and most browsers just invoke a download, instead of displaying the video in a new window. ([Example post.](https://www.construct.net/en/forum/construct-2/bugs-21/pasting-multi-line-content-146389))

## Expected result

Allow video embeds by 3rd party hosters on the forum.

**Comment by TomGullen** [comment]
Allowing Youtube only for now by design - not a bug but will consider in future.
