### ISSUE TITLE
Beta release not shown if newer stable release out

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#119]
As of the r164.3 stable release, the newest release by date is the stable release r164.3, but the newest beta release is r165.

In this case the releases page does not show that a beta release is available, and the editor.construct.net/beta redirect goes to the latest stable release, not the latest beta release. This means desktop installs that are meant to load the beta release have actually reverted back to the stable release, and anything saved in a newer release cannot be opened in an older release.

Determining whether there is a beta release should be based on release number, not release date. In other words: get both the latest stable release and latest beta release; if the beta release number is higher, use that.

**Comment by F3der1co** [comment]
this problem just cropped up again due to the stable hotfix being released after a new beta cycle had started.
