### ISSUE TITLE
unable to buy via paypal.

### ISSUE THREAD

**Issue by Jaggerbyte** [Scirra/Construct.net-website-bugs#122]
## Problem description

I have attempted twice to buy a license via paypal.

## Steps to reproduce

1. buy a license via paypal on a chrome browser
2. refresh page while the spinning arrow animation is playing. ( in my case i waiting overnight before refreshing. )

## Observed result

. The payment on paypal goes through but the website stays on the payment page with a spining arrow saying to wait this will take a few minutes. after refreshing you get no license but paypal is processing payment.

## Expected result

my goal is to get at least 1 license. and a refund for the other attempt. and make some games.

**Comment by TomGullen** [comment]
This should now be resolved
