### ISSUE TITLE
My old comments are gone? New comments must be approved by moderator.

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct.net-website-bugs#125]
## Problem description

If I click on my profile (https://www.construct.net/en/users/46306/boybacteria) it says that I have made 0 comments, even though a have made several in the past (here's one: https://www.construct.net/en/forum/construct-3/your-construct-creations-9/tiny-alien-featured-us-app-143504?kws=tiny%2balien).

And when I post a new comment it must now be approved by a moderator (Also last time I posted a comment it never showed up).

## Steps to reproduce

1.
2.
3.

**Comment by TomGullen** [comment]
Comments are not forum posts - all looks to be in order.
