### ISSUE TITLE
[Suggestion] Send Email For Service Downtime

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#127]
## Problem description

Major downtimes should be announced with an Email in advance, in order to reliably inform all users. This is currently only being done with a [pinned topic ](https://www.construct.net/en/forum/construct-3/general-discussion-7/scheduled-maintenance-friday-147959)inside the forum, which some people might not visit that often. (Thanks for informing us regardless, some services don't even do that.)

It's common for web services to announce important things like major downtimes with an Email, a couple of days in advance. I hope Scirra has the available resources to do this as well and I'd appreciate any efforts towards improving communication in the future.

_Cheers!_

**Comment by jarnMod** [comment]
Please also post it on Facebook. Probably not too much work

**Comment by TomGullen** [comment]
Thanks for the suggestion, we will notify people ahead of time of any planned downtime going forwards.
