### ISSUE TITLE
Forum Bugs: some forum comments are missing but are there in REPLY

### ISSUE THREAD

**Issue by jobel0092** [Scirra/Construct.net-website-bugs#129]
## Problem description

some forum comments are missing, but when you hit reply and start typing in the box you can see those missing comments below the REPLY area.  However they are still missing when you submit your post.  This is currently happening to me on this thread https://www.construct.net/en/forum/construct-3/how-do-i-8/los-using-or-148294#forumPost992580

## Steps to reproduce

1.reply to forum post
2.
3.

## Observed result

post wasn't there
## Expected result
post should have been there

**Comment by dop2000** [comment]
For me this has been going on for several days now. Every time I refresh any forum page, I see different number of comments, posts and notifications. Often I don't see my own comments, but see others replying to them. If I refresh the page, my comments appear, but others' replies disappear. 
It's as if two webservers are out of sync.
Video:
https://gph.is/g/4DneB76

**Comment by jobel0092** [comment]
its always been a bit wonky... I make many typos and I often edit my posts.. sometimes my edits don't show up, sometimes the whole message disappears... its weird.  I've never seen this behavior from a forum before...

@dop2000  does your issue still still happen Incognito mode?

**Comment by dop2000** [comment]
> sometimes my edits don't show up.

Yeah, this has been going on forever. I also edit my comments a lot and sometimes need to refresh the page many times before the edited version shows up.
But the issue with whole comments and threads disappearing/reappearing is new, it started a few days ago. It seems to be resolved today though.
I didn't try incognito mode, but I did test in another browser (without logging into my Scrirra account) and there was the same problem.

**Comment by armandoalonso** [comment]
yeah this has been going on for a while here is a bug report i filed in june for the same behavior https://github.com/Scirra/Construct.net-website-bugs/issues/104

**Comment by dop2000** [comment]
It's happening again.. 2 years later it's still not fixed!

**Comment by jobel0092** [comment]
I've adjusted to the wonkiness.  I just hit edit and then refresh the page a bunch of times.  Sometimes the edit never shows up, sometimes it does.  If it doesn't show up, I edit it again, and eventually it takes...
