### ISSUE TITLE
search pages not updating correctly

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct.net-website-bugs#13]
## Problem description

When you do a search on the forums and the topic has multiple pages and you click a page number and go to the thread, once in the thread clicking on a new page number changes the thread to the new page but the new page number is not updated. This creates a number of problems such as not being able to select that page number again as it thinks you are still on it, plus you can't tell visually the real page number you are now on.

## Steps to reproduce

type a topic in main search engine.
 Find on with multiple pages.
Click say on the 2nd page.
When the thread loads up click on say page 3.
It still says page 2 and not 3, and you can no longer go back to page 2.

## Observed result

page number no updating

## Expected result

correct page for show and navigation.

**Comment by TomGullen** [comment]
Thanks, fixed in v505
