### ISSUE TITLE
Forum replies being lost

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#130]
On the forum I made two replies to this thread:

https://www.construct.net/en/forum/construct-3/general-discussion-7/c3-operation-logic-148558

The first was a longer post. It never appeared after posting though. The forum index shows it has a reply from me, and for some reason the reply appears in the topic history if you reply again, but it's not there in the main thread view.

I tried making a second post ("test test test") to see if that brought it back, but that vanished too.

The replies are missing on both web-1 and web-2.

**Comment by dop2000** [comment]
@TomGullen 
This issue returns every couple of months and is really annoying. 
You leave a comment and it disappears. You leave another one and suddenly see both. You try to delete a duplicate comment and now there are none.... Please fix this.

![gif](https://media.giphy.com/media/vbgcM6kKRNLm2tF9C1/giphy.gif)

**Comment by TomGullen** [comment]
Sorry for this issue - it's a bug in the old caching code.  To fix this, I need to upgrade the forum to the new caching code which is a big overhaul.  At the moment there are more pressing needs.   This is not forgotten and will be fixed in time.  Sorry I can't give an ETA.
