### ISSUE TITLE
Event expressions 'Help' always error jump

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#132]
## Problem description

This little detail has endured for a long long time.
CONSTRUCT 3 MANUAL SEARCH  very difficult to use.

When I Click The ‘Help’ link on Event dialog.
It always Jump to [EXPRESSIONS](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/expressions) page.

But I just want read the Specific manual.

For example:
When I Edit the Parameters for LineOfSight: Has LOS to object. Click the 'Help'
It will jump to [LOS](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/line-of-sight) not [THE PARAMETERS DIALOG](https://www.construct.net/en/make-games/manuals/construct-3/interface/dialogs/parameters)

SYSTEM CONDITIONS  jump to [SYSTEM CONDITIONS](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-conditions)

SYSTEM ACTIONS jump to [SYSTEM ACTIONS](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-actions)

SYSTEM EXPRESSIONS jump to [SYSTEM EXPRESSIONS](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-expressions)

**Comment by AshleyScirra** [comment]
It's not clear what you are talking about - you initially refer to manual search, which is a website feature, then talk about the C3 editor. I transferred this to the website issue tracker on the assumption it is to do with manual search, but I think you need to clarify what you really mean.

**Comment by XHXIAIEIN** [comment]
Sorry, I'm using Google Translate, it may not be good to convey what I want to say.

What I want to say is  C3 editor.
I think in different dialogs, it should jump to the corresponding help page.

The ‘Help’ button refers to this: [Imgur](https://imgur.com/uCXX6kL)
The example in the picture is 'conditions' -> ''Sprite" -> 'Is overlapping at offset'
When I Click The ‘Help’. It will jump to [THE PARAMETERS DIALOG](https://www.construct.net/en/make-games/manuals/construct-3/interface/dialogs/parameters), But I think it should jump to [Sprite](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/sprite) 

[behavior](https://imgur.com/kTROo7w) action dialogs 'Help' jump to [behavior manuals](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/8-direction)

[system actions](https://imgur.com/yAXXapA) dialogs 'Help' jump to [system-actions manuals](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-actions)

**Comment by AshleyScirra** [comment]
That is currently intentional. You are looking at the Parameters Dialog, so the help takes you to the Parameters Dialog manual entry. That page also already notes that you may need to look elsewhere for specific plugin/behavior help:

> The parameters that are displayed depend on the condition or action that was selected. To find out more about what to enter for each field, check the related documentation in the Plugin reference, Behavior reference or System reference.

In general any suggestions that are not bugs should be posted here: https://construct3.ideas.aha.io/
