### ISSUE TITLE
Can't edit tutorial

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct.net-website-bugs#133]
## Problem description

I can't edit my tutorial: https://www.construct.net/en/tutorials/js-rtfm-cheat-sheet-manuals-2269
Saving changes only saves the metadata (tags, deindexed, level) but not the content (title, content)

## Steps to reproduce

1. Hit edit
2. Make changes
3. Hit save
4. Refresh tutorial page

## Observed result

The tutorial content doesn't update

## Expected result

The tutorial content should update

**Comment by TomGullen** [comment]
I believe this is now fixed.  It can take a second for the change to propagate on both webservers.
