### ISSUE TITLE
Insert Image button doesn't work when replying to posts

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#135]
## Problem description

Insert Image button doesn't work when replying to posts. Nothing happens when you click it.

## Steps to reproduce

1. Reply to post
2. Click insert image

## Observed result

Nothing

## Expected result

Insert image dialog should open.

This button does work when you edit your own comment.

**Comment by luckyrawatlucky** [comment]
Temporary Solution is 
create new post 
Upload images 
copy code and paste it where upload never works

**Comment by dop2000** [comment]
Will this be fixed soon? Many people are complaining that they can't insert images, and I need to explain every time that they need to edit their comment..

**Comment by TomGullen** [comment]
Fixed in next upload
