### ISSUE TITLE
"Formatting Help" is completely broken for comments

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#136]
## Problem description
Doesn't display anything after clicking it. It used to be like in forum posts.

## Steps to reproduce

1. Visit: https://www.construct.net/en/make-games/releases/beta/r191
2. Scroll down and press on "Formatting help"
3. Notice broken behavior

## Observed result

![image](https://user-images.githubusercontent.com/15656049/76778053-7ea38100-67a9-11ea-9f01-a299c0a46f6f.png)

## Expected result
Seems to be a regression since I remember using it last year. Should display formatting options.

**Comment by TomGullen** [comment]
Fixed in next upload
