### ISSUE TITLE
Images, thumbnails and such elements do not display in the store

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#138]
## Problem description

Reported in those forum topics :
https://www.construct.net/en/forum/scirra-website/website-issues-and-feedback-35/scirra-store-images-not-151305
https://www.construct.net/en/forum/scirra-website/website-issues-and-feedback-35/something-wrong-store-151323

## Steps to reproduce

1. Go to the Scirra Online store. 
https://www.scirra.com/store

## Observed result

After a long loading images/thumbnails fail to load and display properly.

## Expected result

Images/thumbnails to load and display properly.

**Comment by TomGullen** [comment]
Thanks, is fixed.
