### ISSUE TITLE
tagging people with space in username

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct.net-website-bugs#14]
## Problem description

Tagging a person in a post with @TomGullen doesn't work if the persons name has a space in it.

eg. @Tom Gullen only tags @Tom

## Steps to reproduce

self explanatory

## Observed result

only first part of username is tagged

## Expected result

tag complete user name so person is alerted.

**Comment by AshleyScirra** [comment]
You can tag people with a space in their name using `[@Tom Gullen]`.

**Comment by TomGullen** [comment]
Ashley is correct, will work with square brackets.
