### ISSUE TITLE
Documentation tree menu not work

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct.net-website-bugs#140]
## Problem description

When I want to change tabs in the documentation in tree menu I cannot. It drops innerHTML error

## Steps to reproduce
1. Go to documentation
2. Select another topic in the tree menu
3. It won't appear because javascript cannot fint the HTML element

## Observed result

Not load the selected topic

## Expected result

Load the selected topic

## Screenshot
![screen](https://user-images.githubusercontent.com/47735877/79636454-0baa7300-8178-11ea-990f-f0492efb1ffc.PNG)

**Comment by TomGullen** [comment]
Fixed in next upload
