### ISSUE TITLE
Forum Light/Dark Theme - Design Issues & Suggestions

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#148]
_Active users has no changes:_
![image](https://user-images.githubusercontent.com/15656049/85750168-c0798700-b709-11ea-9ef5-7f598ca685d7.png)

_Image upload dialog has no changes:_
![image](https://user-images.githubusercontent.com/15656049/85751584-fec37600-b70a-11ea-958f-e8d1bf540a8a.png)

_Search result highlighted text is too bright:_
![image](https://user-images.githubusercontent.com/15656049/85751430-ddfb2080-b70a-11ea-9fce-33ab5b534780.png)

_Tabs are too dark:_
![image](https://user-images.githubusercontent.com/15656049/85747259-6aa3df80-b707-11ea-9410-c8129550211b.png)

_KBD is too bright:_
![image](https://user-images.githubusercontent.com/15656049/85752480-bfe1f000-b70b-11ea-8b25-ada93bc02475.png)

_Not highlighted table elements are too bright:_
![image](https://user-images.githubusercontent.com/15656049/85752629-dc7e2800-b70b-11ea-9e3e-e919abc048b1.png)

_Post highlight is too bright ([sample](https://www.construct.net/en/forum/construct-2/general-discussion-17/big-nw-js-roundup-news-tips-119428#forumPost865886)):_
![image](https://user-images.githubusercontent.com/15656049/85747587-b3f42f00-b707-11ea-8163-02b21e380cf7.png)

_Transparent images have grey background:_
![image](https://user-images.githubusercontent.com/15656049/85747699-cbcbb300-b707-11ea-811d-b8a5a44bcac0.png)

_Warning is too bright*:_
![image](https://user-images.githubusercontent.com/15656049/85747864-f0278f80-b707-11ea-8ea2-da56126480d2.png)

---

```
=== EXAMPLE === 

articleRender .notice.warning {
    background: #4f1618;
    border: 1px solid #ff4549;
}
.notification.error, .notice.warning, .notice.warning p {
    background: #290000;
    border-color: #FF8080;
    color: #e66465;
}
```
_Preview:_
![image](https://user-images.githubusercontent.com/15656049/85748700-8cea2d00-b708-11ea-977d-1396ea425f4e.png)

**Comment by TheRealDannyyy** [comment]
Updated with more design issues.

**Comment by TomGullen** [comment]
All fixed in next upload (ETA 3mins)
