### ISSUE TITLE
Construct 3 does not start if offline in Desktop

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct.net-website-bugs#149]
## Problem description
I am facing 2 issues related offline use of construct 3

1. Construct 3 Desktop version doesn't start if you are offline. This problem i'm facing since desktop version launched. Every morning when i don't start my internet modem and just start my pc and launch construct 3 by click C3 icon then it doesn't do anything. But suppose if i start internet after 1 hour then i don't have to click again on C3 icon to start because it starts automatically because i clicked it 1 hour before.
2. Construct 3 in browser doesn't show preview if we are offline and shows only black screen. But if i start the internet and check preview then it shows preview and even if now i off the internet then preview shows correctly.

To work with construct 3 i need a working internet everyday. Without internet i have nothing. last week my internet not worked for 3 days and i was not even able to launch construct. Even browser version was also not starting. It was like i buy construct 3 subscription but i got nothing. 

## Steps to reproduce

1. Wake up in the morning.
2. Do not start your internet modem.
3. Launch Construct 3 desktop version.

- Launch Construct 3 in browser.
- Open any template file.
- Preview it.

## Observed result

nothing happened

## Expected result

Should launch it offline

## More details

**Affected browsers/platforms:** 
Desktop Version / Browser

**First affected release:** 
Facing this issue since C3 launched.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by luckyrawatlucky** [comment]
Yes I am using Beta release

**Comment by AshleyScirra** [comment]
OK, Tom's updated the server and it should be working again now. However you will need to clear the browser cache and reload Construct 3 online again (being sure to wait for the "ready to use offline" notification) to make sure it works offline in future. In NW.js to clear the cache you have to delete the folder `C:\Users\<username>\AppData\Local\construct3`. Could you give that a go and see if it works?

**Comment by luckyrawatlucky** [comment]
Yes Its working now.
Thanks

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
