### ISSUE TITLE
Report window text not visible in Dark theme

### ISSUE THREAD

**Issue by LanciferStudios** [Scirra/Construct.net-website-bugs#150]
## Problem description

When clicking on the report button for posts, the contents of the window are not visible.
Only way to see text is to use the mouse to highlight the text.

## Steps to reproduce

1. Switch to Dark theme. 
2. Click on any report button on any post. 

## Observed result

https://i.imgur.com/Xmu1W0a.png

## Expected result

https://i.imgur.com/20DJLSG.png

**Comment by TomGullen** [comment]
Fixed
