### ISSUE TITLE
Paypal cannot selected CNY for monthly payment

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#156]
## Problem description

**Paypal** cannot be selected **Chinese Renminbi Yuan(CNY)** for **monthly** payment.
(credit or debit card can selected CNY. or Paypal year of payment)

![Imgur](https://i.imgur.com/mg7iRQK.jpg)

By the way, is there any progress in the payment method using Alipay/WeChat/unionpay card?

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Moved to website issues

**Comment by TomGullen** [comment]
For CNY payments:

**"This currency is supported as a payment currency and a currency balance for in-country PayPal accounts only."**
https://developer.paypal.com/docs/api/reference/currency-codes/

We cannot accept CNY Paypal payments.
