### ISSUE TITLE
Unable to pay

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#164]
## Problem description

I can't pay, whatever I choose payment method(Paypal and Alipay),  when I click 'BUY NOW'  it just comes back to the page.

![buynow](https://user-images.githubusercontent.com/45864744/113308500-d111fa00-9338-11eb-902f-bcd28f04c0e6.gif)

There are some errors in the console

![Snipaste_2021-04-01_22-44-05](https://user-images.githubusercontent.com/45864744/113311334-c86ef300-933b-11eb-9220-9e1e15b41fc1.jpg)
![Snipaste_2021-04-01_22-23-21](https://user-images.githubusercontent.com/45864744/113308571-e2f39d00-9338-11eb-86e4-d105640ec111.jpg)

checkout:1007 
```
GET https://www.paypal.com/sdk/js?client-id=AZfykVhpz6Wacz5qtHLIpRCsd2EH0CncEAX6Z9fzO7deDcH1SjnrV46vgMlJ48P7u6N1LvhABo3C7AfM&disable-funding=credit,card,bancontact&currency=CNY net::ERR_ABORTED 400
```

js:1
```
Failed to load resource: the server responded with a status of 400 ()
```

checkout.js:688 
```
Uncaught ReferenceError: paypal is not defined
    at Object.initPaypal (checkout.js:688)
    at Object.init (checkout.js:264)
    at checkout.js:2076
    at checkout.js:2077 
```

---
Windows 10 
Chrome 89.0.4389.114（x64）

## Steps to reproduce

1.
2.
3.

**Comment by TomGullen** [comment]
Thanks for this - it's caused by Paypal.com 404'ing which is default behaviour in some regions.  I've fixed this for the next upload.
