### ISSUE TITLE
[Forums] Can't upload an image on the forums. Neither [.jpg] nor [.png] works.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct.net-website-bugs#17]
## Problem description

We can't seem to upload any image on the forums. Neither [.jpg] nor [.png] works.

## Observed result

**With PNG :**
![image1](https://user-images.githubusercontent.com/31282960/44977443-a30a8480-af9a-11e8-9b1f-fd238f0b5008.png)

**With JPEG :**
![image2](https://user-images.githubusercontent.com/31282960/44977446-a43bb180-af9a-11e8-99fa-c107d1870f73.png)

## Note

Thank you in advance for looking into this.

**Comment by phillscirra** [comment]
Hi,

sorry for the delay, we changed the upload file system recently and have deployed a few fixes to sort this problem out behind the scenes, do you still experience the issue here?  I'm hoping not, I think we hit all these related issues on the head now!

Regards Phill.

**Comment by Chadori** [comment]
Yeah, it's already resolved for a long time now. Thanks.
I'll just close this.
