### ISSUE TITLE
Homepage cube crash

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct.net-website-bugs#171]
## Problem description

Happened to visit C3 homepage with my older laptop. It's GPU got backlisted around 2020. While on CPU render, the Awsome 3D cube at homepage cause lag.
But when GPU blacklist is ignored, the 3D cube 100% crash it at certain angle, 2-3 sec after homepage is loaded. So user has to directly visit other pages and skip homepage.
 

## Steps to reproduce

1.
2.
3.

**Comment by AshleyScirra** [comment]
There's no point reporting bugs that only happen when you ignore the GPU blacklist. That's what the GPU blacklist is there for: to avoid known bugs and crashes. If you turn it off, you're volunteering to allow those known issues to cause problems.

**Comment by SnipG** [comment]
The cube is just too advanced to be added on frontpage, without some filter or check some internal detail, if something something is enabled show cube, otherwise show 2D image. It had cool 2D image before.

And with google dominance, if you buy gamer rigg - you get full 10year licence of web, if you buy cheaper tech 5-10years. After that, you get limited access.

Just show the difference:
C3 perf test with GPU: 40k sprites on-screen at 30fps -> should enable editor normal use
GPU disabled: it's gets spikey 150-400 sprites on-screen at 30fps. Editor cannot be used in most cases
