### ISSUE TITLE
The construct forums are corrupting urls containing ampersands

### ISSUE THREAD

**Issue by Jcw87** [Scirra/Construct.net-website-bugs#173]
## Problem description

If you insert a URL into a post with BBCode, and that URL contains an ampersand, clicking the link will result in an incorrect redirect.

## Steps to reproduce

1. Create any post on the forum that uses BBCode to insert a URL containing an ampersand.
Example:
`[url=https://drive.google.com/file/d/0B40Xy8VSKqoOTnE3bC1xdlEwVEE/view?usp=sharing&resourcekey=0-iqlE98_7mDhZInXkO63jRg]Download[/url]
`
2. Click the link.
3. With the example URL, you SHOULD be able to download the file without asking for my permission. Google will instead give you the option to request access to the file.

## Observed result

The ampersands get XML encoded for some reason, breaking query parameters

## Expected result

The forum redirect should be identical to the URL entered into the BBCode.

## Additional Notes

The URL starts as: `https://drive.google.com/file/d/0B40Xy8VSKqoOTnE3bC1xdlEwVEE/view?usp=sharing&resourcekey=0-iqlE98_7mDhZInXkO63jRg`

The outgoing link tracking converts it to this: `https://www.construct.net/out?u=https%3a%2f%2fdrive.google.com%2ffile%2fd%2f0B40Xy8VSKqoOTnE3bC1xdlEwVEE%2fview%3fusp%3dsharing%26amp%3bresourcekey%3d0-iqlE98_7mDhZInXkO63jRg`
Note that at this point, the URL has already been tainted by XML encoding

According to https://deref.link/, the forums redirect you to:  `https://drive.google.com/file/d/0B40Xy8VSKqoOTnE3bC1xdlEwVEE/view?usp=sharing&amp;resourcekey=0-iqlE98_7mDhZInXkO63jRg`
The ampersand is XML encoded, which breaks the URL

This issue has also been reported on the forums:
https://www.construct.net/en/forum/scirra-website/website-issues-and-feedback-35/construct-forums-corrupting-167598

**Comment by TomGullen** [comment]
Fixed for next upload, thanks for the report.
