### ISSUE TITLE
Black side on landing page cube 

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct.net-website-bugs#178]
## Problem description
I'm on Windows and the Landing page cube looks like this for me in Firefox. 
( Not seen in the video: If I open the page for the first time after a long time the cube is completely black for a while )

https://user-images.githubusercontent.com/18266300/202560371-6b26e3f6-04fd-424a-80ec-477f8647db68.mp4

In Chrome the videos are playing and I only get a black side in the beginning.

## Steps to reproduce

1. Open https://www.construct.net with Firefox on Windows
2. Observe?! xD

## Observed result

A black side on the spinning cube on the landing page and none of the videos playing when viewing the website with Firefox. 

## Expected result

The spinning cube to look the same in every browser or at least not solid black

**Comment by TackerTacker** [comment]
The videos are playing for me now in FireFox, but the same video is still black for me. 
It seems to be an issue with the video itself? 
This is the video that doesn't play, and it doesn't play even if I open it directly via this link https://construct-static.com/videos/v1282/homepage/kiwi-edit.mp4 ( The video plays fine when I download it )
Every other video, like this one for example https://construct-static.com/videos/v1282/construct3/goose.mp4 plays perfectly fine in the browser.

**Comment by TomGullen** [comment]
I've just tested in latest version of Firefox and can't reproduce.  If you clear your cache and ensure you're using the latest version of FF, does it fix the issue?
