### ISSUE TITLE
Service Workers force latest C3 version

### ISSUE THREAD

**Issue by vicbarbosa** [Scirra/Construct.net-website-bugs#181]
## Problem description

If I try to open an older Construct 3 version through, for instance, the Launch r308 button found in this page:
https://www.construct.net/en/make-games/releases/stable/r308

... or by typing the version directly in the search bar, the editor's site will redirect to the root and open the latest version instead.

I can't use it in an annonymous tab because it loses all my plugins and settings.

When this happens, me or my team have to open the browser console and unregister service workers in order to be able to open the correct C3 version.

Reason why this is important in my case: The project sub-folders structure introduced after r308.2 broke my custom git merge tool so my co-workers have to use r308 until I'm able to fix my tool to support the new project's structure. Not a big deal but annoying nonetheless. This also can make my team accidentally save the project in the newer version and potentialy having to revert important commits.

## Steps to reproduce

1. Open Construct in the latest version
2. Wait for offline support to be ready
3. Close Construct
4. Try opening an older version from the releases page

## Observed result

The site redirects to the root, opening the latest version

## Expected result

Should open the version I want regardless if the latest version is cached or not. Maybe add a warning that you are working on an outdated version so other developers don't get stuck in an older version by accident.

**Comment by AshleyScirra** [comment]
It works fine for me. The "launch r308" button takes me to https://editor.construct.net/r308/ where it correctly loads the r308 version, and I have the latest version cached too. It also works fine in an incognito window.

Maybe just clear your browser cache and try again?
