### ISSUE TITLE
official blogs link error

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#182]
## Problem source

[Using lerp with delta-time](https://www.construct.net/en/blogs/ashleys-blog-2/using-lerp-delta-time-924)

>Just to recap, lerp(a, b, x) is a [system expression](https://www.scirra.com/manual/126/system-expressions) that calculates a + x * (b - a). In other words, it returns the number x% of the way from a to b, e.g. lerp(100, 200, 0.25) gives the number 25% of the way from 100 to 200, which is 125. This is called linear interpolation (lerp for short) and is often very useful in game design. dt is short for "delta time", or the time in seconds since the last frame, covered in more detail in the tutorial [delta-time and framerate independence](https://www.scirra.com/tutorials/67/delta-time-and-framerate-independence).

## Expected result

- system expression:
https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-expressions#internalH1Link3

- delta-time and framerate independence
https://www.construct.net/en/tutorials/delta-time-framerate-2

**Comment by AshleyScirra** [comment]
It's a pretty old blog (posted 2015)! I updated the links.
