### ISSUE TITLE
 manuals navigation error

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#183]
## Problem description

[system-expressions](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-expressions#internalH1Link6:~:text=make%20savegames.-,System,-CurrentEventNumber)

You can see 'Save & LoadSystem' here they're mixed together.

![Snipaste_2023-01-07_14-33-53](https://user-images.githubusercontent.com/45864744/211134795-5fb9c1a0-e743-4ea8-a27f-1e909e6ee929.png)

It will cause the jump error when clicking the navigation

![Snipaste_2023-01-07_14-33-52](https://user-images.githubusercontent.com/45864744/211134924-b088ef8e-c877-4d30-9955-1cbd032d6ea9.png)

**Comment by dop2000** [comment]
Yeah, I noticed this too. Looks like shortcuts on the right are broken in many pages. For example here if you click "Expressions", the page scrolls to "Actions"
https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/ajax

https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/gamepad

https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/browser

**Comment by TomGullen** [comment]
Fixed for next upload.
