### ISSUE TITLE
Manual has missing CSS for Dark Mode

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct.net-website-bugs#192]
## Problem description

![image](https://github.com/Scirra/Construct.net-website-bugs/assets/11213825/5d341dbb-2a8d-4225-b2e5-086400cd02e8)

## Steps to reproduce

1. Go here: https://www.construct.net/en/make-games/manuals/addon-sdk/reference/pluginproperty

## Observed result

Text isn't readable

## Expected result

Text is readable

Here is the missing CSS

```CSS
span.ilTag.c5 {
    background: #211F30;
}
```

just add it to darktheme.css

**Comment by TomGullen** [comment]
Fixed for next release
