### ISSUE TITLE
Dropbox links get corrupted when posted on the forum

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#193]
## Problem description

If you paste a dropbox link (and possibly other links) into a forum reply, it gets corrupted.

Correct link:

`https://www.dropbox.com/scl/fi/2ctsvsdcobdem94haxq9j/ManOnARaft.c3p?rlkey=vo4j4louckydqzprwpp0nvp1t&dl=0`

It gets changed to this:

`https://www.dropbox.com/scl/fi/2ctsvsdcobdem94haxq9j/ManOnARaft.c3p?rlkey=vo4j4louckydqzprwpp0nvp1t&amp;dl=0`

Which results in error 400 when clicked.

You can see both examples in this [comment](https://www.construct.net/en/forum/construct-3/how-do-i-8/keep-object-direction-178939#forumPost1097541).

**Comment by TomGullen** [comment]
Fixed for next upload
