### ISSUE TITLE
Tagging yourself in a post sends you a notification

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct.net-website-bugs#194]
## Problem description

If someone tags me in a post and I quote their response, I am technically tagging myself in a post, but then I receive a notification about it.

## Steps to reproduce

1. Tag yourself in a post

## Observed result

![image](https://github.com/Scirra/Construct.net-website-bugs/assets/11213825/a270c821-3136-4648-b521-12d5b2408873)
https://www.construct.net/en/forum/construct-3/general-discussion-7/good-time-construct-great-178657/page-8#forumPost1098013

## Expected result

I shouldn't receive a notification

**Comment by TomGullen** [comment]
Fixed on next upload
