### ISSUE TITLE
Website: Can't see keyboard shortcut keys in manual

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct.net-website-bugs#195]
I'm trying to figure out what shortcut key is meant here but on every browser i try, it fails to load the symbol in the key itself:

![image](https://github.com/Scirra/Construct-bugs/assets/30116964/fd111433-19a7-436d-8651-743642dd3ba2)

**Comment by AshleyScirra** [comment]
Transferred to website issues. This appears to be a duplicate of #166.

**Comment by joelmayer87** [comment]
Thank you @AshleyScirra 

Could you just tell me what key it actually would have been? I'd really like to use this shortcut but noone can answer this enigma for me 😅

**Comment by AshleyScirra** [comment]
They're just the arrow keys: they go in the order up, down, left, right. In other words, using arrow keys moves the selection around the event sheet.

**Comment by joelmayer87** [comment]
Ooooh man i'm so silly... i thought it was a special thing to shift stuff up and down like with Alt+up and down in VS Code or something :D All good then!
