### ISSUE TITLE
Many images are not loading on the website

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#198]
Looks like something has happened to many icons and other images on the website. First my avatar disappeared, I had to re-upload it. And now I noticed that the icons on the Manual page are missing too. 
Here is the Pathfinding behavior page for example, there are text placeholders instead of all images:

![image](https://github.com/Scirra/Construct.net-website-bugs/assets/36763350/38232459-ebd7-4163-8d42-5d6667dd3a78)

**Comment by TomGullen** [comment]
Fixed
