### ISSUE TITLE
Can't Post in Construct 3 Forums - reCAPTCHA is broken

### ISSUE THREAD

**Issue by MessMess333** [Scirra/Construct.net-website-bugs#199]
For the last 3 days the Construct 3 forums are broken for new users because reCAPTCHA is down and you can't pass the test and post new content.
![goete9ri5w3c1](https://github.com/Scirra/Construct.net-website-bugs/assets/16670010/a5effc36-e2fb-4501-a59a-c8c4f3f169cf)

**Comment by TomGullen** [comment]
This should now be fixed.
