### ISSUE TITLE
show just background 

### ISSUE THREAD

**Issue by gloater** [Scirra/Construct.net-website-bugs#20]
## Problem description

in this update r115 it show me just background color , can not load any layers or any thing else . when i changed Advanced runtime to c2 it work good but when i changed to c3 it show me just background color

## Steps to reproduce

1.
2.
3.

**Comment by AshleyScirra** [comment]
This is the website issue tracker. Please file issues with Construct 3 itself here, following all the guidelines: https://github.com/Scirra/Construct-3-bugs
