### ISSUE TITLE
Construct Arcade no support Spine .atlas file

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#201]
## Problem description

If there are .atlas files created by Spine in the game, they will be blocked when uploading to Construct Arcade.

<img width="715" alt="Snipaste_2024-04-12_17-51-58" src="https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/d45d1903-b91d-41cb-9ca7-d17420f5810d">

# zip
Export to Construct Arcade
[SpinePluginTest.zip](https://github.com/Scirra/Construct.net-website-bugs/files/14957132/SpinePluginTest.zip)

Using this plugin
https://github.com/gritsenko/c3_spine_plugin

## Expected result

allow .atlas files

**Comment by TomGullen** [comment]
Fixed for next upload

**Comment by XHXIAIEIN** [comment]
Also includes .AVIF file
https://github.com/Scirra/Construct-bugs/issues/8287
