### ISSUE TITLE
Image does not appear in blog

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#21]
In the latest blog on the debugger: https://www.construct.net/blogs/construct-official-blog-1/introducing-the-new-construct-3-debugger-1036

Under the line "First off, here's what the new debugger looks like." is an image tag with an image of what the debugger looks like. It does not appear in the blog post.

**Comment by phillscirra** [comment]
should be good after the round of finishing touches I made to the uploader.  Can no longer see a problem in this blog post.
