### ISSUE TITLE
Images in side bar don't always load

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct.net-website-bugs#23]
## Problem description

The images in the side bar don't load if they start offscreen, and then you scroll the sidebar to them. This is probably because they exist within their own scroll box, but images are loaded based on the page scroll offset ( which stays 0 in this situation ).

This is probably a pain to modify, but may effect other areas of the website as it grows.

## Steps to reproduce

1. Visit [https://www.construct.net/make-games/manuals/construct-3/behavior-reference](https://www.construct.net/make-games/manuals/construct-3/behavior-reference)
2. Ensure that around half of the sidebar is offscreen, if not resize and reload the page
3. Scroll the sidebar down to the bottom

## Observed result

Placeholder image for plugin reference or system reference.

## Expected result

Icons to have loaded.

**Comment by shortercode** [comment]
You can also see this issue in the preview for forums posts.

**Comment by phillscirra** [comment]
Well that's annoying, I can replicate but as soon as I hit f12 on the browser for the object inspector the icons appear.  It's probably some lazy loading issue with the images. Will continue to investigate further.

**Comment by TomGullen** [comment]
Fixed for next upload - now using HTML lazy loading attribute on images
