### ISSUE TITLE
Navigation error in the translated tutorials on Scirra.com

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#25]
Original report in the forums : https://www.construct.net/forum/scirra-website/website-issues-and-feedback-35/evry-translation-link-are-brok-137183

## Problem description

When browsing a translated tutorial, the first page displays in the translated language, the next pages don't

## Steps to reproduce

1. Visit https://www.scirra.com/tutorials/37/fr/fr
2. Click on page 2 in the top navigation bar

## Observed result

The URL is different in its structure from the first page.
The page displayed is back from the original English tutorial.

## Expected result

The page to be displayed in the same translated language as the first page was.

**Comment by Kyatric** [comment]
It can be manually accessed at the moment (the issue comes from the URL)

For example consider the tutorial "Beginner's guide to Construct 2" in Italian
Its URL on the first page is : https://www.scirra.com/tutorials/37/it/it
If you click to go on the second page it becomes : https://www.scirra.com/tutorials/37/beginners-guide-to-construct-2/it/page-2
But if you modify it to be : https://www.scirra.com/tutorials/37/it/it/page-2 you can access the translated page

Each time you want to access a new page, change the number after "page-" to access it and you should be able to go through the whole tutorial without issue.

**Comment by phillscirra** [comment]
Thanks Kyatric, sorry for the delay in replying.  I'll see if I can give Tom a nudge about this.
