### ISSUE TITLE
Post Formatting Keyboard Shortcuts Don't Work In FireFox

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#26]
## Problem description
When using shortcuts like `CTRL+I` to insert formatting into a post, FireFox just opens up the default browser function (if available) and adds nothing to the post.

## Steps to reproduce
1. Create new forum post in FireFox
2. Try to use any of the available formatting shortcuts
3. Notice that they don't work properly and/or open up default browser functions

## Observed result
Post formatting keyboard shortcuts don't work in FireFox.

## Expected result
Post formatting keyboard shortcuts should work fine in FireFox, just like they do in Chrome.

**Comment by phillscirra** [comment]
Thanks Danny,

should be fixed when we next upload code changes to the website.

Regards Phill.
