### ISSUE TITLE
Post Formatting "Insert Hyperlink" Doesn't Work When Text Is Marked

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#27]
## Problem description
Using the "insert hyperlink" formatting option in forum posts only works when no text is marked.

## Steps to reproduce
1. Create forum post
2. Type any word and select/mark it
3. Notice that the "insert hyperlink" button + shortcut doesn't work

## Observed result
The "insert hyperlink" button no longer works when text is marked. This is a regression since this feature worked fine before.

## Expected result
The "insert hyperlink" button should work just like the other formatting options and add BBcode tags around the selected/marked text.

**Comment by phillscirra** [comment]
Thanks Danny, we'll take a look at it.

Regards Phill.

**Comment by TomGullen** [comment]
Fixed next upload
