### ISSUE TITLE
Addon search doesn't match partial terms

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#28]
In the addon exchange, try the following searches:

"analytics" -> doesn't match "GameAnalytics"
"script" -> doesn't match "JavaScript"
etc.

**Comment by phillscirra** [comment]
Yeah, we haven't got anything too fancy going on here with the searching, doesn't look like we've got full text index searching enabled and/or inflectional searching - but that may be a bit of overkill.

I can change the searching on the name string field to be a little more like a wildcard search, such as;

var results = from u in users
        where SqlMethods.Like(u.FirstName, "%John%")
        select u;

**Comment by phillscirra** [comment]
Gonna add Full-Text searching universally into the system for this.  meanwhile I have written a small stopgap solution for this, as Full-Text search could get involved.

**Comment by bilgekaan** [comment]
I just search for dictionary and it shows the pin behavior and highlights distance. I'm not sure if this is the same issue, if isn't I can file a new bug report.

![image](https://user-images.githubusercontent.com/2965842/49602249-0c82a080-f999-11e8-9601-42fad9a6df11.png)
