### ISSUE TITLE
[Firefox]Irregular format in the posts when seeing the highlights of a search

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#30]
## Problem description

Using Firefox, some of the words are tied one to another as if there was a line jump/or the word wrap is incorrect when checking a topic that was accessed as result of a search (using kws in the URL)

## Steps to reproduce

1. Access https://www.construct.net/forum/game-development/tools-and-resources-27/best-analytics-solution-for-ht-110996?kws=analytics in FireFox

## Observed result

Various posts of the topic from top to bottom:  

Nagval333 - Quote from the previous (correct) post : "I usegoogle analytics"
"can youtellmy what"
Justifun - "I could never getthatone to work"
Headbang Games - "Just setup anaccount"

## Expected result

Proper posts without merging of those words for no good reason.

**Comment by phillscirra** [comment]
Hi Kyatric,

thanks for the bug report..this is a really odd bug, I can replicate here both in chrome and firefox;  its really odd, but it *does* appear to be just related to how the search results are rendered, the original data from the topic appears to be in-tact when you don't run a search.

Need to investigate further!

Regards Phill.

**Comment by VictoryRice** [comment]
Yeah I've been getting this too for several days now. Tried on different browsers and different PCs, it consistently removes spaces between words when looking at forum search results, and also when looking at a post clicked on from search results. 

On this latter point, I can visit this post (for example), and I get the squashed spacing:
[https://www.construct.net/en/forum/construct-3/how-do-i-8/mouse-cursor-over-any-object-125987?kws=object](https://www.construct.net/en/forum/construct-3/how-do-i-8/mouse-cursor-over-any-object-125987?kws=object)
![image](https://user-images.githubusercontent.com/8423528/48227462-412e1880-e357-11e8-8d84-68c48cf06db5.png)

But if I visit it with the ?kws=object URL parameter removed, it looks fine:
[https://www.construct.net/en/forum/construct-3/how-do-i-8/mouse-cursor-over-any-object-125987](https://www.construct.net/en/forum/construct-3/how-do-i-8/mouse-cursor-over-any-object-125987)
![image](https://user-images.githubusercontent.com/8423528/48227490-5acf6000-e357-11e8-8514-9f66dbbe380f.png)

**Comment by Lennaert78** [comment]
@phillscirra,

Looking at the source code of your pages, the format is spewed out like that server side.
Perhaps a remnant of the search feature passing on some trim function to the search results.

**Comment by phillscirra** [comment]
Thanks @VictoryRice and @Lennaert78  for your input; I found the problem was indeed in the server side code.   The behaviour seemed to only affect those words occurring immediately after a highlight - I put in a fix to the code base last week but then fell ill; I don't think we've deployed the fix yet, but it's ready to go.

**Comment by TomGullen** [comment]
Fixed.
