### ISSUE TITLE
Forum Error showing detail site information

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct.net-website-bugs#33]
## Problem description

I am seeing an error in the browser when trying to go into the forum.

The real reason I am writing this is to let you know how much information is being displayed when an error occurs.

## Steps to reproduce

1. Just went to the forums to see new posts
2.
3.

## Observed result

Critical error

This should not of happened. Please contact support.

System.TypeInitializationException: The type initializer for 'GoogleAnalytics' threw an exception. ---> StackExchange.Redis.RedisTimeoutException: Timeout performing GET Currency.1, inst: 80, mgr: Inactive, err: never, queue: 14, qu: 0, qs: 14, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: PRD-VM-WEB-1, serverEndpoint: Unspecified/Construct3.redis.cache.windows.net:6380, keyHashSlot: 2443, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=17,Free=32750,Min=1,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: stackexchange.github.io/StackExchange.Redis/Timeouts) at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120 at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81 at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647 at C3.Code.Controls.Application.Caching.Distributed.DistributedCacheController.Get[T](String cacheKey) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Distributed\DistributedCacheController.cs:line 92 at C3.Code.Controls.Application.Caching.Manager.Manager.Get[T](String key, Func`1 getFromExternFunction, Boolean skipLocalCaches) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Manager.cs:line 158 at C3.Code.Settings.GoogleAnalytics..cctor() in C:\Construct.net\Source\C3Alpha2\Code\Settings.cs:line 552 --- End of inner exception stack trace --- at C3.Code.Helpers.GoogleAnalytics.Functions.ShouldTrackRequest(User currentUser, String ipAddress) in C:\Construct.net\Source\C3Alpha2\Code\Helpers\GoogleAnalytics\Functions.cs:line 12 at ASP.pages_master_pages_global_master.__DataBinding__control20(Object sender, EventArgs e) at System.Web.UI.Control.OnDataBinding(EventArgs e) at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding) at System.Web.UI.Control.DataBindChildren() at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding) at System.Web.UI.Control.DataBindChildren() at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding) at System.Web.UI.Control.DataBindChildren() at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding) at System.Web.UI.Control.DataBindChildren() at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding) at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)StackExchange.Redis.RedisTimeoutException: Timeout performing GET Currency.1, inst: 80, mgr: Inactive, err: never, queue: 14, qu: 0, qs: 14, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: PRD-VM-WEB-1, serverEndpoint: Unspecified/Construct3.redis.cache.windows.net:6380, keyHashSlot: 2443, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=17,Free=32750,Min=1,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: stackexchange.github.io/StackExchange.Redis/Timeouts) at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120 at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81 at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647 at C3.Code.Controls.Application.Caching.Distributed.DistributedCacheController.Get[T](String cacheKey) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Distributed\DistributedCacheController.cs:line 92 at C3.Code.Controls.Application.Caching.Manager.Manager.Get[T](String key, Func`1 getFromExternFunction, Boolean skipLocalCaches) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Manager.cs:line 158 at C3.Code.Settings.GoogleAnalytics..cctor() in C:\Construct.net\Source\C3Alpha2\Code\Settings.cs:line 552
## Expected result

To see forum posts

**Comment by el3um4s** [comment]
**Me too**, I am seeing an error in the browser when trying to go into the forum.

From Italy, with Windows 10

### Critical error

This should not of happened. **Please contact support.**

System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry) at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) at System.Data.SqlClient.SqlConnection.Open() at System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user) at System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe() at System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode() at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query) at System.Data.Linq.DataContext.ExecuteCommand(String command, Object[] parameters) at C3.Code.Callbacks.UserSessionCallbacks.OnPageView(UserSession forSession, Country currentlyViewingRegion) in C:\Construct.net\Source\C3Alpha2\Code\Callbacks\UserSession.cs:line 74 at C3.Pages.Master_Pages.Global.Page_Init(Object sender, EventArgs e) in C:\Construct.net\Source\C3Alpha2\Pages\Master Pages\Global.Master.cs:line 96 at System.Web.UI.Control.OnInit(EventArgs e) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) ClientConnectionId:00000000-0000-0000-0000-000000000000 Error Number:53,State:0,Class:20System.ComponentModel.Win32Exception (0x80004005): The network path was not found

**Comment by phillscirra** [comment]
Thanks guys for the report -- I suspect these errors occurred due to you trying to visit the forum during a time when we were updating the website code.

We try to keep error reports like this to an absolute minimum, as a matter of security concern, but sometimes we miss a few pages, as well as being difficult to control during a website update.

I'll discuss with @TomGullen when I get a moment.

**Comment by TomGullen** [comment]
All resolved
