### ISSUE TITLE
New Construct 3 Front Page Is "Crusty" In FireFox

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#34]
## Problem description
It seems like there is an issue with edge smoothing in FireFox.

## Steps to reproduce
Visit: https://www.construct.net/ using FireFox as a Browser.

## Observed result
FireFox:
![ff_crust](https://user-images.githubusercontent.com/15656049/46157982-37f05d00-c27d-11e8-8b92-8e21a6473e5b.PNG)
![ff_crust2](https://user-images.githubusercontent.com/15656049/46157983-37f05d00-c27d-11e8-8c0e-3406ab762b09.PNG)

## Expected result
Chrome:
![c_smooth](https://user-images.githubusercontent.com/15656049/46157993-3c1c7a80-c27d-11e8-803f-2e23d585baf7.PNG)
![c_smooth2](https://user-images.githubusercontent.com/15656049/46157994-3c1c7a80-c27d-11e8-8917-3c9793efc00b.PNG)

**Comment by TomGullen** [comment]
Thanks for spot, fixed in next upload.

**Comment by TheRealDannyyy** [comment]
Thanks, will make sure to check it out in couple of days.

**Comment by TheRealDannyyy** [comment]
It's fixed, can confirm.
