### ISSUE TITLE
some avatars don't show on forum

### ISSUE THREAD

**Issue by vtrixdev** [Scirra/Construct.net-website-bugs#35]
## Problem description
some of the avatars don't show 
a long description is shown instead,
resulting in bad readability and layout issues on the forums

is this some cache issue or something?
some (not all) have fixed themself by visiting the user page 
a default "no avatar" might be a solution..

## Steps to reproduce
1. example on this link
https://www.construct.net/be/forum/construct-3/general-discussion-7
![capture](https://user-images.githubusercontent.com/30049479/46167288-af31eb00-c295-11e8-932b-c56b82da3d10.JPG)
2. example on this link
https://www.construct.net/be/forum/scirra-website/website-issues-and-feedback-35
![capture2](https://user-images.githubusercontent.com/30049479/46167397-fae49480-c295-11e8-92ab-aae6faa92575.JPG)

## Observed result

some avatars don't show

## Expected result

no empty avatars

**Comment by vtrixdev** [comment]
just saw another one

https://www.construct.net/en/forum/construct-3/general-discussion-7/add-your-construct-3-game-to-y-125345
![cap3](https://user-images.githubusercontent.com/30049479/46907280-7c802780-cf10-11e8-9ed8-d472669d3691.JPG)

**Comment by phillscirra** [comment]
Thanks for the info, I'll check it out.  Not sure what it could be off the top of my head, it does sound caching related but seeing as we changed the upload system recently, best to investigate and make sure.

**Comment by phillscirra** [comment]
Should be good now :)
