### ISSUE TITLE
Releases page launch button not styled any more

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#36]
See the "Launch r120" link under "Latest stable" at: https://www.construct.net/en/make-games/releases

This used to be a red button: https://web.archive.org/web/20171110012305/https://www.construct.net/make-games/releases

It looks like the change is accidental, since the launch button should be emphasised.

**Comment by AshleyScirra** [comment]
The launch button also looks wrong on the release page: https://www.construct.net/en/make-games/releases/beta/r121

**Comment by TomGullen** [comment]
Fixed
