### ISSUE TITLE
Search doesn't work in forums

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#38]
## Problem description

The [search function](https://www.construct.net/en/forum/search) stopped working, it's returning 404 error all the time.

## Steps to reproduce

Click "Search" on the main forum page. Try searching for anything.

## Observed result

Page not found 404

## Expected result

Search results

**Comment by LanciferStudios** [comment]
dop2000 is correct. The search result url is adding an extra "en/" as shown in the following example...

`https://www.construct.net/en/en/forum/search?q=arrays&sc=Forum.1&ffIDs=f8`

When I delete the extra "en/" it works correctly.

The search boxes on the top of each sub-forum works correctly. But we have no advanced search options with that.

**Comment by phillscirra** [comment]
Thanks guys, looking in it.  We've updated the language system in the website, we've had similar "double language" problems in the URL after the website was updated.

**Comment by TomGullen** [comment]
Fixed in next upload
