### ISSUE TITLE
Inserted images not appearing in posts and comments

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#39]
## Problem description

When posting on the forums and you insert an image, quite often it doesn't appear in the post/comment. 

## Steps to reproduce

1. Reply to any post
2. Click on "Insert image", upload a file
3. Click on "Post reply"

## Observed result

Very often there is no image in the message.
Sometimes editing the comment and inserting another image (same file, but different image ID) helps, sometimes not.

## Expected result

Image should be there.

**Comment by phillscirra** [comment]
Hi dop2000, the file upload systems have been rewritten lately, I think we've got all the glitches now; I had a quick test inserted images in the forum and things look well to me; if this is still a problem, I'd appreciate if you'd reopen the issue and provide further details; your issue may relate to a specific image type. Regards Phill.
