### ISSUE TITLE
Construct 3 updated x MINUTES ago

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct.net-website-bugs#40]
## Problem description

New version 's eta is in minutes not in hours/days.

## Steps to reproduce

1. Go to the homepage

## Observed result

![bug](https://user-images.githubusercontent.com/23579630/46660979-95a77200-cbb8-11e8-8d8b-46a991ec1418.gif)

**Comment by AshleyScirra** [comment]
Looks like it's saying minutes when it means hours.

**Comment by phillscirra** [comment]
Should be fixed in next release.
