### ISSUE TITLE
Link "Construct 3 discussion" leads to wrong forum

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#42]
## Problem description

In the new top banner, in Community, the link "Construct 3 discussion" takes to the "How do I forum" instead of the "Construct 3 General" forum.

## Steps to reproduce

1. Over the mouse over the top banner word "Community"
2. Click "Construct 3 Discussion"

## Observed result

The "How do I" forum is displayed

## Expected result

The "Construct 3 General" forum to be displayed

**Comment by TomGullen** [comment]
Fixed next upload
