### ISSUE TITLE
"Following" a construct addon results in 404 not found

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct.net-website-bugs#44]
## Steps to reproduce

1. Visit: https://www.construct.net/en/make-games/addons/189/rot
2. Press the follow button while logged in to attempt to get updates about a particular addon
3. 404 not found.

## Observed result

404 not found page

## Expected result

not sure which page its supposed to take you to, but it should sign your account up for updates of when that plugin gets updated.

**Comment by TomGullen** [comment]
Fixed in next upload.
