### ISSUE TITLE
Addon Documention: tabs exceded the page margins

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct.net-website-bugs#45]
## Problem description

![cattura](https://user-images.githubusercontent.com/23579630/47615664-dad10c80-dab1-11e8-9970-ef909e703e1b.PNG)

![html element now with inline events documentation - construct 3 plugins - edited](https://user-images.githubusercontent.com/23579630/47615658-baa14d80-dab1-11e8-9b33-2203c48f71f7.gif)

## Steps to reproduce

1. go to [https://www.construct.net/en/make-games/addons/190/html-element-now-with-inline-events/documentation](https://www.construct.net/en/make-games/addons/190/html-element-now-with-inline-events/documentation)

**Comment by phillscirra** [comment]
Thanks for bug report, I can see the problem here too and can replicate.  A tweak to one of the styling sheets should fix it.

**Comment by phillscirra** [comment]
Hi el3um4s,

this should be fixed when we next update the website! (probably in the next few days)

Regards Phill.
