### ISSUE TITLE
Changelog page tabs wrong word wrap in FireFox

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct.net-website-bugs#46]
## Problem description

In FireFox, the tabs about "bug fixes", "changes" and so on have the wrong word wrap attribute.
Words can be cut in the middle of itself.
Similar issue to 

## Steps to reproduce

1. Go to https://www.construct.net/en/make-games/releases/beta/r123 r123 changelog with FireFox
2. Slide to the "New features"

## Observed result

The column to the right mentions : 
plugin for gener
ating several

In New additions you can see : 
shortcut for de
bug project,

## Expected result

Correct word wrapping

**Comment by TomGullen** [comment]
Fixed next upload
