### ISSUE TITLE
Comment Reply Notification Doesn't Display Correctly

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#47]
## Problem description

If you get a reply notification for a response to one of your comments in a Construct 3 update thread, it doesn't display correctly.

## Observed result

![c3 notification page](https://user-images.githubusercontent.com/15656049/47663870-2365f400-db9e-11e8-8118-cb74b96523cf.PNG)

## Expected result

I guess the expected results would be to display the actual fetched information and not the function?
Not sure but the screenshot should make things clear for you guys.

**Comment by TomGullen** [comment]
I believe this is now fixed.
