### ISSUE TITLE
Editor CSP broken, breaking NW.js export

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#48]
The editor's CSP has been changed renaming downloads.scirra.com to downloads.construct.net. The editor still needs to download content from downloads.scirra.com since we haven't finished that migration, but the change blocks the editor from connecting to downloads.scirra.com. This is currently preventing NW.js exports working in production.

**Comment by TomGullen** [comment]
Think caused by overwriting old downloads host value instead of creating new value.

This should now be fixed, please close if so.

**Comment by AshleyScirra** [comment]
Yep, looks like it's fixed now.
