### ISSUE TITLE
Construct 3 update notifications no longer working

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#49]
## Problem description

When trying to switch from stable releases to beta releases in C3, there is no notification to update to the latest beta. I suspect something is going wrong with service workers again so this might be a regression.

## Steps to reproduce

1. Use the latest stable release (Construct 3 r120)
2. Go to the settings and switch to beta releases
3. Restart Construct 3 and notice that there is no notification to update to the latest beta

## Observed result

Construct 3 doesn't display the updating dialog after opting into beta releases.

![console](https://user-images.githubusercontent.com/15656049/47927489-bdda7600-dec3-11e8-86ee-ee962a4b144b.png)

## Expected result

Construct 3 should display the updating dialog as usual. 

_I'd also like to recommend an option to manually check for updates inside the settings menu. That would at least give users the option to do things manually in case of an error, while checking for updates._

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 45 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a server-side issue so transferred to website issues.

Version information is hosted at https://editor.construct.net/versions.json, but a recent website update has changed the branch names. The editor is hard-coded to look for "branchName" properties of "Stable" or "Beta", but the server is now serving branch names of "{pages.allReleases.construct3.branches.stable.name}" and "{pages.allReleases.construct3.branches.beta.name}". Since neither matches the expected names it never prompts about updates. Probably got broken by updates for translating the website.

Note providing a manual option to check for updates would not have worked around this.

**Comment by TheRealDannyyy** [comment]
Thanks, good to know how updating works in full detail. @TomGullen or @phillscirra would be nice if you guys could look into this soon, pretty important feature for most C3 users.

**Comment by TomGullen** [comment]
Fixed in next update.  Apologies.

**Comment by TheRealDannyyy** [comment]
Thx, np.
