### ISSUE TITLE
Missing 'Your licenses' link on mobile website

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#5]
Original report by @KioriSun: https://github.com/Scirra/Construct-3-bugs/issues/1586

----

I dont not see anymore an easy way to access the licenses page. I think it used to be in the profile page somewhere, now it's nowhere to be found, i can only access it via the construct editor, by clicking on my avatar and 'view details', then 'Your Licenses'. Which leads [here](https://www.construct.net/profile/licenses) as expected.

I hope you guys re-add it somewhere or point out my mistake if i've missed it. In the meantime i've bookmarked the page.

Thanks

**Comment by TomGullen** [comment]
Included in new menu now.

**Comment by TomGullen** [comment]
Included in new menu now.
