### ISSUE TITLE
Addons not appearing in Addon website list

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct.net-website-bugs#51]
## Problem description

Submitted a new addon, but it's not showing up in the addon repo general listing (it's an effect.) I can directly link to it, but it's not part of the general or effect list.

## Steps to reproduce

https://www.construct.net/en/make-games/addons

Does not show my newly submitted a new addon, but it's not showing up in the addon repo general listing (it's an effect.) I can directly link to it, but it's not part of the general or effect list.

Here's the direct link:
https://construct.net/en/make-games/addons/194/normalmapextended

## Observed result

The effect does not show up on list.

## Expected result

The effect to show up on the list.

**Comment by phillscirra** [comment]
I had a quick check, you haven't "published" your addon yet, hence why it's not visible.  If you revisit the direct link again you should see "Your addon is ready to be published!" and a red publish button in the overview section of the addon?

Give that a click and all should be good.

If you still have trouble, feel free to reopen this issue.

Regards Phill.

**Comment by MikalDev** [comment]
Duh, I forgot I had to 'Edit' again to see the publish button. Thanks and sorry for user error bug.

**Comment by phillscirra** [comment]
no problem, we're here to help :)
