### ISSUE TITLE
Forum - Tab Margins Are Weird/Broken

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#52]
## Problem description

The margins between tabs using the post formatting option, used to be much bigger.
Now they are too close to each other and make tab captions look like a long word.

## Observed result

The margins between tabs are either not working correctly or have been removed.

_Screenshot:_
![tabs](https://user-images.githubusercontent.com/15656049/48224153-3a27fa00-e399-11e8-9c94-44c1bab671ce.PNG)

## Expected result

Tabs need to be clearly separated, so that readers don't get confused.

**Comment by phillscirra** [comment]
Ahh, thanks Danny.  we had another bug recently where the tabs in Addon pages would overlap the side bar on the right on the screen, this change has most likely had a knock on effect in this area of the system...this looks like a screenshot from the forum? do you have a direct link/url to this so I can test further?

Regards Phill.

**Comment by TheRealDannyyy** [comment]
Here are two of my topics which use the new tabs feature:
- https://www.construct.net/en/forum/construct-2/general-discussion-17/updated-25-07-2018-the-big-nw-119428
- https://www.construct.net/en/forum/extending-construct-2/addons-29/plugin-simple-native-like-mous-131418

**Comment by phillscirra** [comment]
OK, I've revisited and further tweaked, spent a bit more time on it.  It should be good in both addon's and the forum's now.  I've added a faint border around each tab element now, to help separate each of the tab items.

**Comment by TheRealDannyyy** [comment]
Lookin good, thx!

**Comment by TheRealDannyyy** [comment]
Nevermind it's looking good on mobile but not desktop. I guess the update has not been pushed there yet.

**Comment by phillscirra** [comment]
yeah. it didn't appear to go through today; I pushed the changes this morning and they didn't get logged on Tom's machine for today's update.

**Comment by TheRealDannyyy** [comment]
I can now confirm that it's indeed looking good.
Thanks again!
