### ISSUE TITLE
[Suggestion] Public API 

### ISSUE THREAD

**Issue by Armaldio** [Scirra/Construct.net-website-bugs#53]
It could be very usefull to expose an API for any third party app to interact with the Construct environment.
I could think of it about querying addon datas or even submitting addons, querying infos about a user or even use the scirra login to log into a 3rd party app. There are many possibilities.

**Comment by AshleyScirra** [comment]
Do you have some specific, high-value use-cases? Without some compelling reasons to justify it I think we are just too busy to do anything like this...

**Comment by Armaldio** [comment]
I had disscussed that with Tom already long time ago and he told me that ws a great idea.
About some specific case, I have this tool "Addon Intaller" https://github.com/WebCreationClub/construct-addon-installer which aim to ease the process of installing C2 addon from your own store, howerver it's difficult because it's not reliable: it's just a crawler that read the page to gather informations. It's enough for basic task but for example, when promptingwether to install or not, I can't check locally if the plugin is already installed because I don"t have access to the online id, or I can"t check local version against online one because I dont't have this value exposed in the code either.
I don"t know if it's a *high-value* case, but I just think that if you want more interaction with 3rd party tools, it's a top notch feature 👍

**Comment by phillscirra** [comment]
Addon Installer looks interesting, although I'd imagine the reason that it's unreliable is that it's scrapping the html code in someway and is sensitive to any changes we make to the web pages.

Tagging @TomGullen as the guy to comment further on this.  I was oddly thinking about practical reasons to have an API backend, but personally couldn't think of good enough reasons to concrete a good argument.

**Comment by TomGullen** [comment]
Can't see any immediate reason to have it for most parts of the site, but does make sense for addons, arcade and perhaps the store.

**Comment by phillscirra** [comment]
I'm gonna close this issue for the time being, but it'll remain in our list of enhancements just in case we want to return to this in the future,
