### ISSUE TITLE
Threads linked from forum search have broken layouts

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct.net-website-bugs#55]
## Problem description

When searching for a thread if you follow the link the thread appears in a broken state.

[This](https://www.construct.net/en/forum/extending-construct-2/addons-29/plugin-not-quite-random-118071?kws=random) particular one seems extremely broken.

## Steps to reproduce

1. Search for the word "random"
2. Select a result
3. Observe issue

## Observed result

- the keyword is highlighted, but the last character is missing for some reason
- the posts are missing all their spaces
- moving onto the next page loses the keyword
- words longer than a line don't break
- some threads seem to loose all styling past a point

## Expected result

To view the thread, with the searched term highlighted.

**Comment by TomGullen** [comment]
Fixed.
