### ISSUE TITLE
Scirra arcade comments not loading

### ISSUE THREAD

**Issue by Vincent31415** [Scirra/Construct.net-website-bugs#60]
## Problem description

On my game, 3-3 Gravity, I have 5 sections of comments. The first 4 will load; but the 5th won't, no matter how long I wait.
## Steps to reproduce

1.Go to  https://www.scirra.com/arcade/action-games/3-3-gravity-34277
2.Try to go to the 5th page of comments.

## Observed result

It just stays on the current section of comments. It doesn't load the 5th.

## Expected result
I expected it to load the 5th section of comments.

**Comment by TomGullen** [comment]
We'll be releasing a new arcade this year and moving everything over.  Afraid not willing to spend time on maintaining current arcade right now.  Sorry for the problems - but bear with me!

**Comment by Vincent31415** [comment]
No worries! Do you know what month to expect it?

Thanks,

-Vincent

[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]

**Comment by TomGullen** [comment]
No ETA I'm afraid.
