### ISSUE TITLE
Forum Tags - Design Enhancements

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#63]
## Problem description

First off, really appreciate the new tags feature on the forums! Surely makes things like filtering topics easier. 

While I have no problems with the actual feature, I would like to request some design improvements for tags inside the topic itself. I think they are a bit too distracting at the moment.

_Example Topic:_
![tags](https://user-images.githubusercontent.com/15656049/51457763-e94a5f80-1d52-11e9-88f7-52e6703f93ec.PNG)

## Suggestions
I think making them smaller would help in general. When it comes to positioning and alignment, perhaps putting them on the side or on top of the 1st topic post could help. Below are two quick mockups I made. 

Pretty straightforward but feel free to ask me any questions for more details. They are based on other common forum designs out there. Would only require CSS changes I think but not sure.

_Mockup 1:_
![suggestion1](https://user-images.githubusercontent.com/15656049/51458296-fec08900-1d54-11e9-8996-ac2be45ee338.png)

_Mockup 2:_
![suggestion2](https://user-images.githubusercontent.com/15656049/51458301-0122e300-1d55-11e9-87c3-576e49d4ca3d.png)

**Comment by TomGullen** [comment]
I like this suggestion, too busy to implement any time soon but keeping open for now.
