### ISSUE TITLE
Report button needs fixing

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#68]
## Problem description

Report button on forum posts/comments doesn't give any feedback when clicked.
Apparently it does work and the report is sent, but users don't see it. There should be some message displayed like "report submitted".

## Steps to reproduce

Click Report on any comment.

## Observed result

Nothing.

## Expected result

Some feedback.

**Comment by Kyatric** [comment]
In Firefox, the actual "dialog" that provides the option to put a comment and select the type of report does not display at all and gives the impression that nothing happens.

In Chrome, it works as expected.

A fix is required for at least FF indeed.

**Comment by TomGullen** [comment]
Fixed in next upload
