### ISSUE TITLE
Bugged website banners

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct.net-website-bugs#69]
## Problem description

Some website banners are bugged, when you move mouse to or over them.

## Steps to reproduce

See video instead:
[BuggedBanners.zip](https://github.com/Scirra/Construct.net-website-bugs/files/2865788/BuggedBanners.zip)

## Observed result

Website banners are bugged and move way to hacky.

Banners that i mean:
![buggedbanners](https://user-images.githubusercontent.com/28864889/52799402-6f23a700-3082-11e9-861b-6f08f18cf967.jpg)

## Expected result

No bugged behavior. Or maybe more rare, i occasionaly saw it few times, i tried it more now and hacky behavior reproduces very often.

**Comment by TomGullen** [comment]
Removed hover effect for next release - seems to be causing issues on some browsers.  Good spot also!
