### ISSUE TITLE
No repro Uncaught (in promise)

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#7]
Original report by @JeFawk: https://github.com/Scirra/Construct-3-bugs/issues/1592

----------

## Problem description

I barely get these like once a week or so. There are no repro steps that I can give out since the occurrence is extremely tiny (i preview projects about between 50 to 300 times a day) so if you know something that could fix it based on these errors, that's great!

Note that adblock plus is disabled.

![image](https://user-images.githubusercontent.com/7268697/40139744-93cffa14-5959-11e8-984e-76ad8ca864e3.png)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 3 gb (44.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by phillscirra** [comment]
Is this a confirmed website bug here? do we need to do anything? I've noticed a few github bugs closed by Ash, but not actually closed...is this a result of the bugs being moved in github?

**Comment by AshleyScirra** [comment]
I think the problem is the log shows some fetches on editor.construct.net failing with a 504 error (gateway timeout), which I suppose could point to some kind of issue with the website... but without more information there might not be anything we can do.

I "moved" some issues from the C3 repo to the website bugs repo by copy-pasting them and closing the old report, which might be a bit confusing. There's a new "transfer issue" feature on GitHub now which should make it easier.

**Comment by TomGullen** [comment]
Have you seen this in a while?

**Comment by AshleyScirra** [comment]
Not seen or heard of this for a while now so I guess we can just close. It might have been a precursor to the CloudFlare HTTP/2 issue.
