### ISSUE TITLE
Tutorials transferred from scirra.com to construct.net missing attachments

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#70]
## Problem description

All tutorials from scirra.com were recently transferred to construct.net 
And seems like all attached files were lost in the process. Please restore them.

## Steps to reproduce

This is my tutorial and it used to have 2 files attached, now I don't see them anywhere:
https://www.construct.net/en/tutorials/sending-data-from-construct-2-3-to-google-spreadsheet-1447

I checked many other tutorials that I remember having demo projects attached to them, and now there are no attachments.

## Observed result

No attachments.

## Expected result

Attachments should be available.

**Comment by TomGullen** [comment]
Confirmed bug, will look into fixing this ASAP.

**Comment by TomGullen** [comment]
This is now resolved.  All attachments currently will be on last page of tutorial, am working on including them in left menu next.
