### ISSUE TITLE
Suggestion - forum layout

### ISSUE THREAD

**Issue by vtrixdev** [Scirra/Construct.net-website-bugs#71]
Something that really bothers me while reading things on the forum,
It feels like everything on the forum screams for attention, i just want to go after a while

some examples:

- construct team badges (huge) 
- tags: white letters on red tags + bold text
- titles: red bold text
- red page buttons
- stars before the titles + huge icon before the item
- combination cyancolor with red text on top 
- many colorfull icons everywhere

some of these look good on its own, but combined its really way to much,
I think with some tweaks i could be much better

![image](https://user-images.githubusercontent.com/30049479/53183527-cf26ca00-35fb-11e9-85ea-dd4392cf450b.png)

**Comment by AshleyScirra** [comment]
Please post suggestions to the website category on the suggestions platform: https://construct3.ideas.aha.io

**Comment by vtrixdev** [comment]
I was redirected from here 

https://www.construct.net/en/forum/scirra-website/website-issues-and-feedback-35/please-report-issues-and-sugge-138188

**Comment by AshleyScirra** [comment]
I edited that thread to point to the suggestions platform for suggestions.
