### ISSUE TITLE
Email notification of new release leads to unavailable page

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct.net-website-bugs#72]
## Problem description

Got an email "Construct 3 r139 (beta) - Now available" with a red button "view and launch r139" which leads to non-existent page 

## Attach a .c3p

Not required

## Steps to reproduce

1. Open "Construct 3 r139 (beta) - Now available" email
2. Click "view and launch r139" button
3. Observe result

## Observed result

Email button links to https://www.construct.net/make-games/releases/beta/r139 - it is unavailable

## Expected result

Directly accessing website to https://www.construct.net/en/make-games/releases/beta/r139 (I've noted than **/en/** part in the middle) works fine.
Please note that the affected browser is Google Chrome with Russian system language - maybe some redirection failed.

## More details

**Affected browsers/platforms:** 

Affected browser Google Chrome with Russian system language.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TomGullen** [comment]
Hi, what error do you receive when you click the link?  Does it 404 or throw an exception?

**Comment by AshleyScirra** [comment]
This forum post might be related: https://www.construct.net/en/forum/construct-3/general-discussion-7/why-not-a-link-to-the-instruct-142086

Looks like issues with link redirection for non-English users.

**Comment by Madiosn** [comment]
This is not a 404 error. The error is called: "Load cannot follow more than 20 redirection"

**Comment by TomGullen** [comment]
This should now be fixed.  See:
https://github.com/Scirra/Construct.net-website-bugs/issues/73
