### ISSUE TITLE
Crush the sait construct [redirect error in Russian]

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct.net-website-bugs#73]
Load cannot follow more than 20 redirections

https://www.construct.net/ru

## Steps to reproduce

with the release of r139 stopped loading many sections of the site. Maybe it wasn't just a coincidence. 

"Load cannot follow more than 20 redirections"

clearing the cache, selecting another browser does not help. Change the Internet provider as well. This problem occurs on the hosting configuration side

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks like another case of #72

**Comment by TomGullen** [comment]
Does it fail in another browser?  Suspect this might be a caching issue.

**Comment by Madiosn** [comment]
The problem occurs in all browsers, that is, the problem is not a local character. The same problem remains when using different Internet providers and different computers and smartphones. This problem can occur both because of the cache on the user’s (my) side and deeper on the side of the site itself when it is configured. This is due to setting up a large number of redirects.The problem goes as I understand it at the regional level, for example, users from other countries do not observe it, everything is fine with them. But those who are in Russia can no longer visit the site.

**Comment by TomGullen** [comment]
Are you able to email me on tom@scirra.com with your IP address please?  This will help me diagnose the issue.

**Comment by Madiosn** [comment]
Yes, im Send you.

**Comment by TomGullen** [comment]
Thank you for that.  Do these links for you work, or does it redirect?

https://www.construct.net/fr/tutorials/le-guide-du-d-butant-construct-3-20
https://www.construct.net/en/tutorials/le-guide-du-d-butant-construct-3-20

**Comment by Madiosn** [comment]
https://www.construct.net/fr/tutorials/le-guide-du-d-butant-construct-3-20
https://www.construct.net/en/tutorials/le-guide-du-d-butant-construct-3-20
Its link is work. its OK!


https://www.construct.net/ - NOT WORK
https://www.construct.net/en - its OK
https://www.construct.net/ru - NOT WORK
https://www.construct.net/make-games/manuals/construct-3/project-primitives/projects - NOT WORK

**Comment by TomGullen** [comment]
Thank you for all your help, much appreciated!

Can you please retest all those URL's in Chrome, but before you do it:
 - Open Dev tools by pressing F12
 - Click network tab
 - Check "Disable cache"
 - Keep dev tools open then visit the URLs again

Do they all work when you do this?

**Comment by Madiosn** [comment]
Doesn't work. Many Redirects 

Screen
`https://yadi.sk/i/I0hddT9-sRVIkA`

**Comment by TomGullen** [comment]
Can you screenshot those redirects in the network log so I can see all fields please?  (Like your previous screenshot but expand the columns)

**Comment by Madiosn** [comment]
Yes of course.

Video ScreenShot
https://yadi.sk/i/RR3wNi31dFWgMA

**Comment by Madiosn** [comment]
Screenshot adress
https://yadi.sk/i/bclRYVasU9F4Tw

**Comment by TomGullen** [comment]
Thank you, if you make the request and right click in the network content area and select "Save all HAR with content" and email me the file please?   EG:

![1](https://user-images.githubusercontent.com/998934/53488959-b13be800-3a87-11e9-9791-615ad5ea3f51.png)

**Comment by Madiosn** [comment]
Yes, im send you HAR file)

**Comment by TomGullen** [comment]
Brilliant thank you for all that, I can now reproduce the error.  I'll issue a fix today.

**Comment by Madiosn** [comment]
Thank you very much we will wait)

**Comment by TomGullen** [comment]
I've published a fix - can you confirm if the URL's now work?

If not, please check "Disable" cache in the "Network" tab (F12) and re-try.

**Comment by Madiosn** [comment]
Yes its working now!! Big sanks)

**Comment by TomGullen** [comment]
No problem, thank you for bearing with me!  Am closing as resolved.
