### ISSUE TITLE
 ask you to modify the system for selecting an object and a layer on which the object is located.

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct.net-website-bugs#74]
## Problem description

I ask you to modify the system for selecting an object and a layer on which the object is located.

Now all the work is happening on the layer that was selected initially, which is extremely inconvenient. When you select an object on another layer and say you copy it, it is inserted on that layer on which you find it initially. As a result, then you have to manually check all objects and mix them in layers.

It would be logical that when selecting an object, the program automatically switched to its layer and all the work was done on the layer of the given object.

This will greatly simplify life.
## Steps to reproduce

1.
2.
3.

**Comment by AshleyScirra** [comment]
This is not a website bug, and we do not accept suggestions in bug reports. Please post Construct 3 suggestions here: https://construct3.ideas.aha.io/
