### ISSUE TITLE
Forum posts parse HTML entities

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#77]
If you try to enter `&nbsp;` in a forum post, it disappears. Presumably it's being interpreted as a real HTML entity and adding a non-breaking space instead of the text. This came up here in a discussion involving HTML entities: https://www.construct.net/en/forum/construct-3/how-do-i-8/how-do-i-add-spacing-within-bb-142112#forumPost967851

Since forum posts don't allow HTML it makes sense they shouldn't allow HTML entities either. It will also make technical discussions about HTML easier.

**Comment by TomGullen** [comment]
Fixed next upload
