### ISSUE TITLE
Missing text in privacy policy

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#78]
In the privacy policy: https://www.construct.net/en/privacy-policy

Under the text "For legal reasons:" there is a section that is not visible, because its markup uses `<ul>text</ul>` instead of `<ul><li>text</li></ul>`. Therefore the following text is not displayed in the actual page:

> Responding to requests by government or law enforcement authorities conducting an investigation.
To detect, prevent, or otherwise address fraud, security or technical issues and software piracy (e.g., to confirm that software is genuine and properly licensed), helping to protect you as well as Scirra.

**Comment by TomGullen** [comment]
Fixed next upload
