### ISSUE TITLE
editor.construct.net/beta does not redirect to latest release

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#80]
editor.construct.net/beta redirects to the latest beta release only. It should redirect to the newest release if it's stable.

Currently stable release is r142 but editor.construct.net/beta redirects to r141.3, which is now out of date. Since the beta desktop download of C3 points at /beta, it keeps loading an out of date release.

**Comment by TomGullen** [comment]
Changed for next upload
