### ISSUE TITLE
editor.construct.net no longer updating to latest version

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#82]
Users visiting editor.construct.net are getting an old version which no longer updates. This is because the service worker requests https://editor.construct.net/index.html as part of loading the new version. However recently (presumably after a website update) this URL now returns 404 not found (test in incognito window to observe this, else the service worker will serve a cached file). If any file fails to load, the update bails out and serves the old version. This URL needs to be allowed to load for Construct updates to work.

**Comment by TomGullen** [comment]
Fixed for next upload.
