### ISSUE TITLE
Forum quote formatting and user tagging not working

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#84]
This forum reply uses both a quote (starting with >) and a username tag. Neither are displayed, the whole post is plaintext: https://www.construct.net/en/forum/construct-3/general-discussion-7/future-c3-build-convert-old-142924#forumPost970919

It looks like username tags only sometimes work, but the quote formatting seems to be not working at all at the moment.

**Comment by TomGullen** [comment]
Fixed for next upload, although rendered post is cached so changes won't be reflected until cache is wiped.  Leaving issue open as a reminder to myself to build in long expiry for rendered text or think of another solution.

**Comment by TomGullen** [comment]
Found a solution for next upload.  Closing issue.
