### ISSUE TITLE
Norifications page not working, returns 500 exception

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct.net-website-bugs#88]
## Problem description

The website shows that I have unread notifications, but when I click Notifications link, it says "WHOOPS! The server returned a 500 exception. "

## Steps to reproduce

Try to open this link:
https://www.construct.net/en/profile/notifications

## Observed result

500 exception

## Expected result

List of notifications

Tested in Firefox and Chrome, same error.

**Comment by TomGullen** [comment]
Have updated site recently, are you still receiving this error?

**Comment by dop2000** [comment]
Hi Tom. It works fine now, thank you!

**Comment by TomGullen** [comment]
No problem!
