### ISSUE TITLE
Critical error This should not of happened. Please contact support.

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct.net-website-bugs#89]
## Problem description

Entering in the site show this instead of the site.

## Steps to reproduce

Go to [https://www.construct.net/en](https://www.construct.net/en)

## Observed result

![image](https://user-images.githubusercontent.com/23579630/56460449-15ea3380-63a3-11e9-8edc-9b53450ba3af.png)

## Expected result

View site

## Error code:

**Critical error**
This should not of happened. Please contact support.

System.Threading.Tasks.TaskCanceledException: A task was canceled. at StackExchange.Redis.ConnectionMultiplexer.Wait(Task task) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 543 at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisSubscriber.cs:line 471 at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.SubscribeToCacheKey(RedisChannel cacheKey, Action`2 onMessageReceived) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Redis\PubSub\PubSubController.cs:line 45 at C3.Code.Controls.Application.Caching.Manager.Manager.Callbacks.OnGotten[T](String cacheKey, CacheType fromType, T objectGot) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Callbacks.cs:line 99 at C3.Code.Controls.Application.Caching.Manager.Manager.Get[T](String key, Func`1 getFromExternFunction, Boolean skipLocalCaches) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Manager.cs:line 131 at C3.Code.Caching.ProductDiscountCaching.GetForIP(String ipAddress) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 96 at C3.Code.Caching.ProductDiscountCaching.GetIPDiscounts(String ipAddress, Boolean showUnavailable) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 78 at C3.Code.Caching.ProductDiscountCaching.GetVisitorDiscounts(User forUser, String forIPAddress, Boolean showUnavailable) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 40 at C3.Code.Caching.ProductDiscountCaching.GetClaimableVisitorDiscounts(User forUser, String forIPAddress) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 33 at C3.PageControls.TopMenu.TopMenu.Page_Load(Object sender, EventArgs e) in C:\Construct.net\Source\C3Alpha2\PageControls\TopMenu\TopMenu.ascx.cs:line 61 at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Critical error**
This should not of happened. Please contact support.

System.Threading.Tasks.TaskCanceledException: A task was canceled. at StackExchange.Redis.ConnectionMultiplexer.Wait(Task task) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 543 at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisSubscriber.cs:line 471 at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.SubscribeToCacheKey(RedisChannel cacheKey, Action`2 onMessageReceived) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Redis\PubSub\PubSubController.cs:line 45 at C3.Code.Controls.Application.Caching.Manager.Manager.Callbacks.OnGotten[T](String cacheKey, CacheType fromType, T objectGot) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Callbacks.cs:line 99 at C3.Code.Controls.Application.Caching.Manager.Manager.Get[T](String key, Func`1 getFromExternFunction, Boolean skipLocalCaches) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Manager.cs:line 131 at C3.Code.Caching.ProductDiscountCaching.GetForUserID(Int32 userID) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 72 at C3.Code.Caching.ProductDiscountCaching.GetUsersDiscounts(Int32 userID, Boolean showUnavailable) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 53 at C3.Code.Caching.ProductDiscountCaching.GetVisitorDiscounts(User forUser, String forIPAddress, Boolean showUnavailable) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 44 at C3.Code.Caching.ProductDiscountCaching.GetClaimableVisitorDiscounts(User forUser, String forIPAddress) in C:\Construct.net\Source\C3Alpha2\Code\Caching\ProductDiscountCaching.cs:line 33 at C3.PageControls.TopMenu.TopMenu.Page_Load(Object sender, EventArgs e) in C:\Construct.net\Source\C3Alpha2\PageControls\TopMenu\TopMenu.ascx.cs:line 61 at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by TomGullen** [comment]
Thanks, appears to of been an Azure blip, am still investigating this.  Cleared up on it's own, so closing for now.
