### ISSUE TITLE
Edit blog is not working

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#9]
Original report by @pooyaGames: https://github.com/Scirra/Construct-3-bugs/issues/1597

-------

When i try to edit my blog or after creating one i see this page 
![screenshot 2018-05-17 19 26 07](https://user-images.githubusercontent.com/426713/40185636-4aa20d78-5a08-11e8-9948-de5c274aded1.png)

**Comment by phillscirra** [comment]
I think is working! I visit the link and it appears fine to me!
