### ISSUE TITLE
"Course completed" message appears a little too early

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#90]
If the last tutorial on a course has multiple pages, it shows "Course completed!" in green at the bottom of page 1. This looks a little premature, since there's still several pages of tutorial left. E.g.:

https://www.construct.net/en/tutorials/multiplayer-tutorial-real-598?vic=12

Perhaps that should only appear on the last page?

**Comment by TomGullen** [comment]
Fixed for next upload.
