### ISSUE TITLE
Suggestion - User's Plugins Area and User Search

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct.net-website-bugs#93]
## Problem description
Sometimes I can't find users other plugins. I think we need more organised Addons page.

1.) You can add plugins area for user's profile page. We can see user's all plugins

![image](https://user-images.githubusercontent.com/13033837/57026791-46538c80-6c43-11e9-9f7e-7b7d5cabeff1.png)

2.) You can add "user search support" and "filter user" areas for Addons page

![image](https://user-images.githubusercontent.com/13033837/57026883-83b81a00-6c43-11e9-94b4-cabe70aedf8c.png)

**Comment by AshleyScirra** [comment]
Please file suggestions at https://construct3.ideas.aha.io/ in the website category.
