### ISSUE TITLE
key is not defined

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct.net-website-bugs#94]
## Problem description

A couple of days ago there was an error when working in the browser with construct 3.

The message constantly flies: Construct 3 beta / key is not defined
## Steps to reproduce
The message comes out after a certain amount of time constantly when working in the browser

The browser does not matter - it happens in all browsers
1.
2.
3.

## Observed result
screen
https://yadi.sk/i/iZ8YGTb9QbqYIw

**Comment by AshleyScirra** [comment]
Please post this to the Construct 3 bugs tracker, not the website bugs, and follow all the guidelines otherwise we cannot investigate.
