### ISSUE TITLE
Wrong Construct 3 editor version in links

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#95]
## Problem description
Seems like there is a minor problem with subversions in links.

## Observed result
https://editor.construct.net/r1472/
https://www.construct.net/en/make-games/releases/beta/r1472

## Expected result
https://editor.construct.net/r147-2/
https://www.construct.net/en/make-games/releases/beta/r147-2

**Comment by TheRealDannyyy** [comment]
This is still an issue and probably confuses a lot of Construct 3 users. 
Could this please get fixed by someone from the website team?

It's also affecting my 3rd party [desktop launcher](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-3-desktop-simple-lau-139502) application.
![image](https://user-images.githubusercontent.com/15656049/58336482-17949480-7e44-11e9-9a5d-f593cb78df15.png)

**Comment by TomGullen** [comment]
Problem is dots are not a permitted URL character and are stripped out - this is obviously not as can cause a collision between two releases.  I'll look into getting this fixed by replacing the dots with dashes.

**Comment by TomGullen** [comment]
Fixed for future releases, will now dash them.  Will be repairing the incorrect release name soon.

**Comment by TheRealDannyyy** [comment]
Thanks for looking into it!

**Comment by TomGullen** [comment]
Should now all be fixed.
