### ISSUE TITLE
@-tagging users in forum doesn't seem to work any more

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#99]
Twice I've tried to tag @shortercode in the forum and it's just turned in to `@-` instead, e.g.:

https://www.construct.net/en/forum/construct-3/general-discussion-7/encountering-strange-error-144099#forumPost975715

**Comment by shortercode** [comment]
I think this has been around awhile, had a few users mention that they couldn't tag me. Not sure whats special about my user name. I've just been using the `[@username]` format instead.
